version: '3.9'

services:

  cvo:
    image: umrobotics/cvo:latest
    container_name: slam
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "TERM=xterm-256color"
      - "XAUTHORITY"
    working_dir: "/home/root"
    privileged: true
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .zshrc:/root/.zshrc:rw
      - .zsh_history:/root/.zsh_history:rw
      - /home/$USER/Projects/:/home/root/ws/
      - /home/$USER/Projects/curly_slam/data/:/home/root/data/
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: /bin/zsh
